# Form implementation generated from reading ui file 'icon_screen.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(654, 282)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/newlogo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_selectFile = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_selectFile.setFont(font)
        self.pushButton_selectFile.setStyleSheet("")
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.horizontalLayout.addWidget(self.pushButton_selectFile)
        self.lineEdit_filePath = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.horizontalLayout.addWidget(self.lineEdit_filePath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_fileName = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.horizontalLayout_2.addWidget(self.lineEdit_fileName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_newFile = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_newFile.setFont(font)
        self.pushButton_newFile.setStyleSheet("")
        self.pushButton_newFile.setObjectName("pushButton_newFile")
        self.verticalLayout.addWidget(self.pushButton_newFile)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_convertFile = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_convertFile.setFont(font)
        self.pushButton_convertFile.setStyleSheet("")
        self.pushButton_convertFile.setObjectName("pushButton_convertFile")
        self.verticalLayout.addWidget(self.pushButton_convertFile)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Create Icon File"))
        self.label.setText(_translate("Form", "Select a file to convert:"))
        self.pushButton_selectFile.setText(_translate("Form", "Choose File"))
        self.label_2.setText(_translate("Form", "Icon File Name:"))
        self.pushButton_newFile.setText(_translate("Form", "New File"))
        self.pushButton_convertFile.setText(_translate("Form", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
